/*
Generated on 2022-02-04 00:37
This is a file generated by make_catalog.py from string catalog files.
It contain message string constant definition, with a predictable name.
Sources are:
    messages.cat
*/

#ifndef _MESSAGES_H
#define _MESSAGES_H

// keeping track of source files
#ifdef __GNUC__
#pragma GCC dependency "messages.cat" Modified file "messages.cat", catalog header need to be regenerated
#endif // __GNUC__

// ERRORS 
const char ERRORS_OUT_OF_MEM[] = "Failed to allocate memory for %s";
const char ERRORS_UNEXPECTED_EOF[] = "Unexpected EOF while %s";


#endif // _MESSAGES_H
